int = 정수형

type() 데이터의 형태를 정해주는 함수

In [17]:
a = 1; print(type(a))

<class 'int'>


정수형을 float함수를 통해 복소수화 할 수 있다

In [1]:
a = 1; a = float(a); print(type(a))

<class 'float'>


복소수를 int함수로 정수형으로 변경시킬 수도 있다

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


숫자형을 따옴표로 문자형 데이터로 변환할 수 있다

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


대괄호는 리스트 같은 데이터형의 해당 순서의 인덱스 값을 검색할 때 쓰인다

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


대괄호는 list 형으로 지정할 때

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


소괄호는 튜플 데이터로 지정할 때 쓰인다

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


딕셔너리는 중괄호를 이용하고 포함된 인덱스 값들이 1:1 대응관계를 지니고 있다.

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


튜플을 인덱스로 포함한 리스트도 어찌됐건 리스트 형이다.

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])